### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by djsavvy** [catppuccin/catppuccin#40] opened 2022-01-27 23:48 UTC
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
This theme is stunning! Thank you so much for creating it. 

Would it be possible for us to make a light variant?

**Comment by andreasgrafen** [comment] 2022-01-27 23:58
The possibility of a light variant has been discussed quite a bit on Discord already iirc. It think there are some plans for it, but no durther information on how and/or when that would be a thing.

As there are quite a few colours already, that just every so slightly don't work on light backgrounds, it's a little bit more compliacted than wished for to actually port this to a light palette properly as it would require extensive tweaking of the accent colours.

**Comment by Pocco81** [comment] 2022-01-28 04:32
Duplicate of https://github.com/catppuccin/nvim/issues/80. However, since this one is in the correct place I'm going to close the other one.

**Comment by andreasgrafen** [comment] 2022-01-30 09:28
[https://jsfiddle.net/3kf2cso9/](https://jsfiddle.net/3kf2cso9/)
I'll just put this here because that makes it easier to find. Discord can get quite messy. :D

**Comment by Pocco81** [comment] 2022-05-26 23:56
**_Alakazam!_** Your wish has been granted: https://github.com/catppuccin/catppuccin/releases/tag/v0.2.0

**Closed by Pocco81** 2022-05-26 23:56 UTC
Labels: enhancement, help wanted

**Comment by felixmr1** [comment] 2022-05-30 19:48
@Pocco81 Does this mean that a light theme will be developed (and that just the theme now supports it). Or that I can actually enable a light theme as of now :thinking: ?

**Comment by Pocco81** [comment] 2022-05-30 21:29
@felixmr1 the light theme is already available: https://github.com/catppuccin/catppuccin/tree/main#-palettes

The team of devs is currently working on making the 4 new palettes (including the light theme which btw is called "Latte") available on every port.

**Comment by djsavvy** [comment] 2022-05-31 01:03
Thank you so much! Excited to try it out :)
