### ISSUE TITLE
OldTwitter

### ISSUE THREAD

**Issue by isabelincorp** [catppuccin/catppuccin#2127] opened 2023-08-01 04:39 UTC
### Link to repository

https://github.com/isabelincorp/oldtwitter

### Screenshots

![preview](https://github.com/catppuccin/catppuccin/assets/114378481/c939b903-f592-407f-a71a-23afe4261bb9)

### Any additional comments?

I discussed the creation process of this port [over here](https://discord.com/channels/907385605422448742/1125801228971028581). As mentioned before in there, this wouldn't be classified as a user style port because it doesn't use Stylus for theming, instead utilizing the tools built into the OldTwitter extension.

### Submission Guidelines

- [x] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment] 2023-08-06 00:55
Reviewed on discord in the [OldTwitter Forum](https://discord.com/channels/907385605422448742/1125801228971028581), only very minor comments that has resulted in a FAQ section being added for common actions to troubleshoot the extension not working as intended.

Overall, looks good to me. I'm happy for it to be transferred over to the organisation!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by isabelincorp** [comment] 2023-08-06 00:58
Transferring over the repository now! I'

**Closed** 2023-08-06 02:07 UTC
