### ISSUE TITLE
RStudio IDE

### ISSUE THREAD

**Issue by AngelBerihuete** [catppuccin/catppuccin#2137] opened 2023-08-09 23:22 UTC
### Link to repository

https://github.com/AngelBerihuete/rstudio

### Screenshots

[RStudio IDE](https://posit.co/products/open-source/rstudio/) screenshots:

[Late](https://raw.githubusercontent.com/AngelBerihuete/rstudio/main/assets/late.webp)

[Frappé](https://raw.githubusercontent.com/AngelBerihuete/rstudio/main/assets/frappe.webp)

[Macchiato](https://raw.githubusercontent.com/AngelBerihuete/rstudio/main/assets/macchiato.webp)

[Mocha](https://raw.githubusercontent.com/AngelBerihuete/rstudio/main/assets/mocha.webp)

### Submission Guidelines

- [x] I have read and followed Catppuccin's submission guidelines.

**Comment by AngelBerihuete** [comment] 2023-10-06 06:53
Hi. It'd would be great catppuccin org accept this port! Many thanks. 

Concerning your request, I've update the stars/issues/contributors badges to point to ```catppuccin/rstudio```. Also I've read again the [Sytle guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#%EF%B8%8F-style-guide) to understand your comment about *more formalised syntax colours*. I need a more detailed explanation to know what changes are needed in ```rstudio``` repo due the updated style guide.

**Comment by backwardspy** [comment] 2023-10-06 09:47
hey, thanks for that! looks like `a` tags around the badges images still need an update:

`<a href="https://github.com/catppuccin/template/stargazers">`

> I need a more detailed explanation to know what changes are needed in `rstudio` repo due the updated style guide.

no problem! we now have a [`code editors` section](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#code-editors) of the guide that was designed to match our best editor ports as closely as possible. as a result, some of the colours you've chosen for the rstudio port might not match our choices anymore. for example, it looks like numbers in rstudio are currently `mauve` and constants are `teal`, whereas in the updated style guide they're both now specified to be `peach`.

as i said i don't think it's worth blocking the transfer on this, but it would be a nice improvement to make.

**Comment by AngelBerihuete** [comment] 2023-10-13 10:20
Many thanks for explaining! I've changed `template` by `rstudio`. The repo is updated. 
Also I'll create a develop branch to check the code editors sections in this port.

**Comment by backwardspy** [comment] 2023-10-13 12:23
great!
@catppuccin/core ready for invite

**Comment by nekowinston** [comment] 2023-10-13 12:34
Sent, thanks for the ping :)

**Comment by sgoudham** [comment] 2023-10-27 18:04
Hi @AngelBerihuete, if you need any guidance on how to transfer the repository to the organisation, please read  ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account).

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

Let us know if you have any questions :+1:

**Comment by AngelBerihuete** [comment] 2023-10-31 09:44
Hi @sgoudham, I've transferred the repo. Please, If you don't mind, check if I've done correctly. 

Many thanks!

**Closed** 2023-10-31 22:30 UTC
Labels: waiting for transfer
