### ISSUE TITLE
Starship Prompt

### ISSUE THREAD

**Issue by etrigan63** [catppuccin/catppuccin#1823] opened 2023-01-21 05:50 UTC
**Are you available to help in the creation of this port? 😄 (optional)**
YES

**Additional context 📷 (optional)**
https://github.com/etrigan63/catppuccin-starship

All finished.

**Comment by rubyowo** [comment] 2023-01-21 05:52
please look at #203

**Comment by etrigan63** [comment] 2023-01-21 06:14
This is done and I am offering it for inclusion.

**Comment by nekowinston** [comment] 2023-01-22 18:01
Closing this as a duplicate of #203. This isn't planned.

**Closed by nekowinston** 2023-01-22 18:01 UTC
Labels: port request
