### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by mip29** [catppuccin/catppuccin#1698] opened 2022-10-12 04:27 UTC
**Are you available to help in the creation of this port? 😄 (optional)**
Yes, but I have 0 experience with creating themes. A slack theme is pretty basic though, so I might be able to help out.

**Additional context 📷 (optional)**
Add any other context or screenshots about the port request here.

**Comment by nekowinston** [comment] 2022-10-12 04:29
Hi there 👋 

Thanks for raising this issue, but I'm going to close it as a duplicate of https://github.com/catppuccin/catppuccin/issues/166

**Closed by nekowinston** 2022-10-12 04:29 UTC
Labels: port request
