### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by CelestialN3ko** [catppuccin/catppuccin#29] opened 2022-01-16 21:36 UTC
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
![image](https://user-images.githubusercontent.com/63929325/149678983-32532c57-2841-4217-b12b-25452d37689f.png)

**Comment by andreasgrafen** [comment] 2022-01-16 21:47
Duplicate of #19 
Nice looking port tho! c:

**Comment by Felice-Neko** [comment] 2022-01-16 22:02
Yea, I only noticed it when I wanted to submit this request. It's different tho.

**Comment by andreasgrafen** [comment] 2022-01-16 22:07
Well, it's a port request, I guess? No worries tho, I'm sure it's fine.
Don't you have a repo for the ports too? Might be nice to link that, no? o:

**Comment by CelestialN3ko** [comment] 2022-01-16 22:14
[https://github.com/CelestialN3ko/catppuccin-firefox](url)

**Comment by Pocco81** [comment] 2022-01-17 01:29
@CelestialN3ko before it's added to the org and the theme pushed to Firefox's official theme website, could you add instructions on how to use the theme to the README?

**Comment by CelestialN3ko** [comment] 2022-01-17 20:46
I made some changes to my repo and now the readme is also done. Also the themes are on firefox's add-ons, I would appreciate it if some people can try them and give me feedback.

**Comment by CelestialN3ko** [comment] 2022-01-18 19:18
I fixed some things, everything should be done now.

**Comment by Pocco81** [comment] 2022-01-23 17:28
Closing this issue because the port is ready: https://github.com/catppuccin/firefox

**Closed by Pocco81** 2022-01-23 17:28 UTC
Labels: port request
