### ISSUE TITLE
Starship (shell prompt)

### ISSUE THREAD

**Issue by GoodBoyNeon** [catppuccin/catppuccin#1731] opened 2022-11-11 11:44 UTC
**Are you available to help in the creation of this port? 😄 (optional)**
no ;(

**Additional context 📷 (optional)**
 A very minimal but functional prompt would be great! ik it's easier said than done but as it is a cross-platform shell prompt, many would be interested in it! (It has 30k stars on GitHub!)

**Comment by kkrypt0nn** [comment] 2022-11-11 11:46
For that you don't need a separate port. It's your terminal itself so you'd need to get the port of your terminal.

I have starship and my terminal themed and looks the way it should
![image](https://user-images.githubusercontent.com/43011723/201334126-4d74f671-8bc2-47bb-a34c-5b32c4d157a4.png)

**Comment by sgoudham** [comment] 2022-11-11 11:51
Closing this as it's a duplicate of #203

**Comment by sgoudham** [comment] 2022-11-11 11:51
Closing this as it's a duplicate of #203

**Closed by sgoudham** 2022-11-11 11:51 UTC
Labels: port request
