### ISSUE TITLE
Zed

### ISSUE THREAD

**Issue by tecandrew** [catppuccin/catppuccin#2262] opened 2024-02-07 23:13 UTC
### Link to repository

https://github.com/tecandrew/zed.git

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/21319730/1598c2f2-5348-4888-a305-55ae8fd61039)

![image](https://github.com/catppuccin/catppuccin/assets/21319730/9cc4078d-4eca-4366-9a35-13cc22a6c19d)

![image](https://github.com/catppuccin/catppuccin/assets/21319730/2f75778e-09d0-47f9-8b32-21d4eb465203)

![image](https://github.com/catppuccin/catppuccin/assets/21319730/141aeca4-9c10-473b-8916-b94ea22745f8)

### Catppuccin

- the cursor colors were used for each flavor, but made it hard to read when highlighting the in terminal (highlight color == cursor color), so I adjusted each flavor's cursor color slightly
  - the highlight color in the editor panes was changed to use the same terminal cursor color
- color fields set to `null` falls back to Zed default color (not sure what this is), but mostly look OK

### Zed

- most of the coloring was transferred over using Zed's vscode theme importer tool [noted in their blog](https://zed.dev/blog/user-themes-now-in-preview)
~~- custom color themes currently only available in [Zed Preview](https://zed.dev/releases/preview)~~
- Zed JSON color scheme defined [here](https://zed.dev/schema/themes/v0.1.0.json)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

---
edit:

~~there's a slight issue with the selection highlight color not being used in the terminal, and has been identified as a defect https://github.com/zed-industries/zed/issues/7532~~

Fixed in [v0.123.2-pre](https://github.com/zed-industries/zed/releases/tag/v0.123.2-pre). Should be in Stable soon

**Comment by uncenter** [comment] 2024-02-08 11:51
I can confirm now issues with it so far, looks really good. Nice job @tecandrew!

**Comment by viralams** [comment] 2024-02-09 11:18
This is fantastic. I dont see any issues either. Awesome work! @tecandrew

**Comment by kjvdven** [comment] 2024-02-14 09:20
Looks awesome! Thnx for the port.

I also use the VS Code theme, but as [flat appearance](https://github.com/catppuccin/vscode?tab=readme-ov-file#flat-appearance) with minimal set, could you add that as a variation? 

Also the colours look a little different, but maybe that is because flat appearance.

<img width="1278" alt="Screenshot 2024-02-14 at 10 14 50" src="https://github.com/catppuccin/catppuccin/assets/306806/bf012dc1-4b9a-4c31-bbdd-097308fa029a">

Now I hope we can set the catppuccin icons in the future in Zed

**Comment by wonderbeel** [comment] 2024-02-15 08:39
Can add my 2 cents after using this theme for a couple of days and trying to tweak it:

- Borders are too high contrast (this is personal preference but for example the VS Code theme is not as strong) so I tried to reduce them going from overlay1/0 to surface 1/0, also there is a weird border around the entire window but it seems to be a generic issue with dark themes (it happens also with built in one dark but not with one light, so I guess that it is just an issue with zed)
- As already noted ghost items use a color that works well in the title bar and tab bar but not so well in the toolbar: looking at other themes the best solution seems to put this value to transparent

Couple of screenshots:

![Screenshot 2024-02-15 alle 09 18 25](https://github.com/catppuccin/catppuccin/assets/1643060/a3186385-e754-4a19-8f07-4c1f57273ae8)
(@tecandrew theme)

![Screenshot 2024-02-15 alle 09 38 42](https://github.com/catppuccin/catppuccin/assets/1643060/e1673891-5581-4d95-8777-09cbe75c46db)
(my tweaks)

![Screenshot 2024-02-15 alle 09 30 45](https://github.com/catppuccin/catppuccin/assets/1643060/7d615bda-2b7e-4cc0-a21b-be5f6696d9a6)
![Screenshot 2024-02-15 alle 09 30 53](https://github.com/catppuccin/catppuccin/assets/1643060/3b648d29-8024-457d-872a-ba5d14bf94b4)
(one dark and one light as a reference)

**Comment by kjvdven** [comment] 2024-02-15 13:06
>    That being said, I'm curious why the `.js` file in @kjvdven's screenshot has every single variable in `red` because that definitely is incorrect.

Do you need something from me to research the issue?

**Comment by tecandrew** [comment] 2024-02-19 04:30
> Hey 👋, thanks for working on this! I've just got a few comments regarding the theme and the codebase:
> 
> ## Theme
> 1. Overall it looks good! Looks like the VSCode importer got us most of the way there :D
>    In regards to the syntax highlighting, it looks like Zed is using [treesitter](https://zed.dev/docs/adding-new-languages#defining-syntax-highlighting-rules). Funnily enough, we're still in the process of updating our style guide ([docs(style-guide)!: improve and define more highlights #2109](https://github.com/catppuccin/catppuccin/pull/2109)) to explicitly define semantic highlights. Its similar enough to VSCode/Intellij/etc which is pretty good, considering Zed hasn't fully finalised its schema.
>    That being said, I'm curious why the `.js` file in @kjvdven's screenshot has every single variable in `red` because that definitely is incorrect.
> 2. Could you revert the background colour of the text on the top bar here:
>    ![image](https://private-user-images.githubusercontent.com/58985301/304889505-b9e6dff7-43cf-4370-ad97-deaf3ce4c63c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTQwODEsIm5iZiI6MTcwODMxMzc4MSwicGF0aCI6Ii81ODk4NTMwMS8zMDQ4ODk1MDUtYjllNmRmZjctNDNjZi00MzcwLWFkOTctZGVhZjNjZTRjNjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlM2UwZWY0YzI4MmUzN2U5YWM1YWQ4MDYwYmVjODViOWE2MDA4MjMxNzJlZThiZTY4YzlhNmI4MTAxYmZhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KV8yFdx157PHkCmNX-EsufRvgYsXwe6cP73p8nhQ7C0)
>    I think it'd look much better if it matched the background colour of `base`
> 
> ## Codebase
> 1. I believe the changes to the file tree have been made, I'd appreciate if you could re-generate the catwalk images to reflect that.
> 2. Please update the [README badges](https://github.com/tecandrew/zed/blob/06af8a8d11c9a92f5a0018790903d4e66e1bf336/README.md?plain=1#L8-L12) to point towards `catppuccin/zed`.
> 3. Please convert the [README asset links](https://github.com/tecandrew/zed/blob/06af8a8d11c9a92f5a0018790903d4e66e1bf336/README.md?plain=1#L14-L35) to be [relative urls](https://github.blog/2013-01-31-relative-links-in-markup-files/).
> 4. I think the [README Usage](https://github.com/tecandrew/zed?tab=readme-ov-file#usage) section could be simplified to the following:
>    ```
>    1. Create your custom theme folder if you haven't already.
>    	```bash
>    	mkdir ~/.config/zed/themes/
>    	```
>    2. Download the [catppuccin.json](./catppuccin.json) file into the theme folder.
>    3. Open Zed.
>    4. Select your Catppuccin theme in the dropdown shown after hitting ( `cmd+k`, `cmd+t` )
>    ```
> 5. This isn't necessary for the transfer into the organisation, but this repository could benefit from using [whiskers](https://github.com/catppuccin/toolbox/tree/main/whiskers), our new **work-in-progress** port creation helper tool, which is aimed at generating catppuccin ports via handlebars template files. I recently added [single-file support](https://github.com/catppuccin/toolbox/tree/main/whiskers#single-file-support) which would allow it to be used here. (it's still unreleased so you'd have to install straight from source)
> 
> Think we'll be good to transfer the repository into the organisation after the above changes have been implemented!

@sgoudham Got all but the last one in the repo 👍🏽 never heard of the `whiskers` tool until now: would have definitely helped a bit when i got started on this! 🫠

other things addressed was update the borders as well: the lower contrast looks does look a bit better. `null` value was tried too, but looks like Zed defaults to some sort of 'light yellow' color

regarding the Red color, the importer transferred over the ["correct"](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#rainbow-parameters--local-variables) color for the variables, but seems like there's 2 'flavors' for variables  defined by zed to set: https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L289

throughout my testing on some local projects i can't seem to tell the affects on it. their schema doesn't have documentation notes on it either 🙃

**Comment by wonderbeel** [comment] 2024-02-19 07:35
Just an heads up, I was looking at the [extensions](https://github.com/zed-industries/extensions) repo and noticed that there is already a catppuccin theme that seems to be [this](https://github.com/ssaunderss/zed-catppuccin): it seems to be a theme generated with the importer from VS Code instead of hand tuned but it is already there in the centralized extensions repo  🫠.

**Comment by sgoudham** [comment] 2024-02-19 10:29
Thanks for making the changes I outlined @tecandrew

In regards to the red colour, the syntax highlighting keys _seem_ to be 1:1 mapping to treesitter so I think we'd want to change our instance of `variable` to `text`, as previously defined in [catppuccin/nvim](https://github.com/catppuccin/nvim/blob/9703f227bfab20d04bcee62d2f08f1795723b4ae/lua/catppuccin/groups/integrations/treesitter.lua#L17). This should stop the entire file being red if there is no LSP defined providing another set of highlights. I'm unsure about `variable.special` since that's not even defined in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights) but makes sense to change that to `text` as well.

I get the feeling that we'll need to iteratively improve on the syntax highlighting so I'm not too bothered about getting it close to our editors right now, that being said, I've just noticed some things that we can easily line up: 

(I'm assuming that Zed will be following the syntax highlights defined in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights))

1. [`boolean`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L154) and [`constant`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L169) should be `peach`.
2. [`string.regex`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L259), [`string.escape`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L254) and [`string.special`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L264) should be `pink`.
4. [`string.special.symbol`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L269) should be `flamingo`.
5. [`tag`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L275) should be `blue`.
6. [`variable`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L289) and [`variable.special`](https://github.com/tecandrew/zed/blob/ac91f746cadd48eef030e0b8be3734bd74e19e7b/catppuccin.json#L294) should be `text`. (as discussed above)

For testing, I'd recommend that you check out our [samples](https://github.com/catppuccin/catppuccin/tree/main/samples) directory which has code samples for a bunch of popular languages. You could probably have Zed open on one side and VSCode on the other and review them both - making sure that nothing is too out of the ordinary.

Hopefully should be good to transfer into the organisation after these changes since the UI/Syntax Highlighting is coming along nicely!

**Comment by sgoudham** [comment] 2024-02-19 10:33
> Just an heads up, I was looking at the [extensions](https://github.com/zed-industries/extensions) repo and noticed that there is already a catppuccin theme that seems to be [this](https://github.com/ssaunderss/zed-catppuccin): it seems to be a theme generated with the importer from VS Code instead of hand tuned but it is already there in the centralized extensions repo 🫠.

Yeah I noticed this too, I think it makes sense to try and upstream the theme here once merged and available as `catppuccin/zed`.

**Comment by tecandrew** [comment] 2024-02-20 23:12
set the coloring recommendations you mentioned to be similar to treesitter. the sample codes are great! found some discrepancies that the importer didn't get quite right.

few things I noticed from the samples:

- the classes themeselves (when attributes are used) seem to be Red and this is affected by the `variable.special` color. so I set it to that instead of `text` to be similar to vscode. (right is current Zed). classes when functions are used/set are colored differently and left alone to be `text` color

![image](https://github.com/catppuccin/catppuccin/assets/21319730/24431ba8-a931-42b1-88e1-572dbb552cbb)

- the brackets are colored differently in vscode and change the more nested they are. Zed however doesn't seem to do this, so it's set to the Teal color (set by the importer tool)

![image](https://github.com/catppuccin/catppuccin/assets/21319730/a85390f9-5e7c-455d-837b-5b3cd34becbc)


- the last thing is the cursor/selection coloring seems to be fixed in the latest Zed Preview! so i set those as well. found out that Zed color theming accepts the modern web `#rrggbbaa` hex color notation, so I set it to 40% opacity for the selection.
https://github.com/zed-industries/zed/issues/7532#issuecomment-1950620977

**Comment by sgoudham** [comment] 2024-02-20 23:38
Cheers! Thanks for updating it to be in line with VSCode @tecandrew 

I think what you've done with the brackets and variables is good given the limitations! 

The only change that I'd be looking for now is regenerating the `catwalk` previews on the main README so that the selection highlight isn't yellow (although I suppose it's only in preview - maybe worth mentioning that preview is recommended given that syntax highlighting is still evolving / being bug-fixed?) 

In any case, the `catwalk` preview can be easily regenerated at any point so I'm happy to see this transferred into the organisation!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164 (in this case, category would be `code_editor`)

**Comment by tecandrew** [comment] 2024-02-20 23:50
no prob! I regenerated the catwalk images, but seemed like GitHub's relative links render thing took a bit to update the README previews. it should be good now 😄 

from the Zed discord, staff mentioned they release a new Preview and Stable version every week. so likely the selection bug fix should get to Stable fairly soon

**Closed** 2024-02-21 00:38 UTC
Labels: waiting for transfer
