### ISSUE TITLE
Youtube Music

### ISSUE THREAD

**Issue by rubyowo** [catppuccin/catppuccin#1705] opened 2022-10-23 12:15 UTC
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
https://github.com/rubyowo/youtubemusic
first time making a stylus theme so it probably needs a lots of reworking

**Comment by nekowinston** [comment] 2022-10-23 12:26
Closing this as a duplicate of #197, please leave your comment there :)

**Closed by nekowinston** 2022-10-23 12:26 UTC
Labels: port request
