### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by Dukeatron** [catppuccin/catppuccin#196] opened 2022-07-14 06:01 UTC
**Are you available to help in the creation of this port? 😄**
Yes

**Additional context 📷 (optional)**
[Screenshot here](https://imgur.com/a/1XxRW3L)

**Repo link**: [here](https://github.com/Dukeatron/steam)

**Comment by WitherCubes** [comment] 2022-07-14 07:19
Duplicate of #118.

**Comment by nekowinston** [comment] 2022-07-23 16:25
Closing this in favour of #118. The Repo has now been transferred to the Org, to further collaborate there.

**Closed by nekowinston** 2022-07-23 16:25 UTC
Labels: port request
